name: vocal_coach
version: 0.0.1
author: Matias Meno <m@tias.me>
description: Small project to help doing vocal exercises
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  logging: ^0.11.0
  polymer: ^1.0.0-rc.6
  web_components: ^0.12.0
  reflectable: ^0.3.0

  test: ^0.12.5

  sass: '^0.4.2'
transformers:
- sass:
    executable: sassc
- web_components:
    entry_points:
      - web/index.html
- reflectable:
    entry_points:
      - web/index.dart
